from supabase import create_client
import os
from dotenv import load_dotenv
from datetime import timedelta, date
from send_email import send_email

load_dotenv()

supabase = create_client(
    os.environ.get("SUPABASE_URL"),
    os.environ.get("SUPABASE_SECRET_KEY")
)

def get_ending_contracts():
    today = date.today()
    threshold = today + timedelta(days=31)
    # ending_contracts = []
    try:
        response = supabase.table("clients").select("client_name, contract_no, end_date").gte('end_date', today.isoformat()).lte('end_date', threshold.isoformat()).execute()
        for client in response.data:
            print(f"{client['client_name']} (Contract No. {client['contract_no']}) - Ending {client['end_date']}")     
            # ending_contracts.append({'client_name': client['client_name'], 'contract_no': client['contract_no'], 'end_date': client['end_date']})

        return response.data or []   
    except Exception as e:
        print(e)

# Send email about contracts ending before a month
def send_contract_reminder():
    contracts = get_ending_contracts()
    if not contracts or len(contracts) == 0:
        print("No expiring contracts found. So no email notification will be sent.")
        return

    # dynamic HTML table rows
    table_rows = "".join(
        f"""
        <tr style="border-bottom: 1px solid #e2e8f0;">
          <td style="padding: 12px; font-weight: 600; color: #1e293b;">{c['client_name']}</td>
          <td style="padding: 12px; color: #475569; font-family: monospace; font-size: 13px;">{c['contract_no']}</td>
          <td style="padding: 12px; color: #dc2626; font-weight: 600;">{c['end_date']}</td>
        </tr>
        """
        for c in contracts
    )

    # HTML email layout
    html_message = f"""
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
      </head>
      <body style="margin: 0; padding: 24px; background-color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #334155;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; border: 1px solid #e2e8f0; overflow: hidden; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);">
          
          <!-- Header -->
          <div style="background-color: #1e293b; color: #ffffff; padding: 20px 24px;">
            <h2 style="margin: 0; font-size: 18px; font-weight: 600; letter-spacing: -0.025em;">Contract Expiry Alert</h2>
            <p style="margin: 4px 0 0 0; font-size: 13px; color: #94a3b8;">Automated Notification • For your information</p>
          </div>

          <!-- Body -->
          <div style="padding: 24px;">
            <p style="margin: 0 0 20px 0; font-size: 14px; line-height: 1.5; color: #475569;">
              The following <strong>{len(contracts)} contract(s)</strong> are scheduled to finish within the next <strong>30 days</strong>
            </p>

            <!-- Table -->
            <table style="width: 100%; border-collapse: collapse; font-size: 14px; text-align: left;">
              <thead>
                <tr style="background-color: #f1f5f9; border-bottom: 2px solid #cbd5e1;">
                  <th style="padding: 10px 12px; color: #475569; font-size: 12px; font-weight: 700; text-transform: uppercase;">Client Name</th>
                  <th style="padding: 10px 12px; color: #475569; font-size: 12px; font-weight: 700; text-transform: uppercase;">Contract No.</th>
                  <th style="padding: 10px 12px; color: #475569; font-size: 12px; font-weight: 700; text-transform: uppercase;">Completion Date</th>
                </tr>
              </thead>
              <tbody>
                {table_rows}
              </tbody>
            </table>
          </div>

          <!-- Footer -->
          <div style="background-color: #f8fafc; padding: 16px 24px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; text-align: center;">
            This is an automated operational notice generated by the Diddy Party.
          </div>
        </div>
      </body>
    </html>
    """
    send_email(
        to_address='gurkha.forces@gmail.com',
        # to_address='limbuc489@gmail.com',
        subject='Contract Ending Reminder',
        message=html_message
    )






